#!/usr/bin/env python3
"""
Merge researched datasheet URLs into seed.json and write research-log.md.

Findings are keyed by the item's Model / SKU string exactly as it appears in
the workbook, so a merge is idempotent and re-runnable: it only ever fills a
blank spec_url, never overwrites one that already came from the source data
or that was entered by hand in the page.

Usage:
    python merge_research.py            # merge and write
    python merge_research.py --dry-run  # report only
"""

from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
SEED = HERE / "seed.json"
FINDINGS = HERE / "research-findings.json"
LOG = HERE / "research-log.md"

# Items whose "model" names a service, warranty or bespoke fabrication rather
# than a purchasable product. There is no datasheet to find; recording why
# keeps the coverage number honest instead of looking like a research miss.
NOT_A_PRODUCT = {
    "Factory Commissioning": "service - Lutron factory commissioning, not a product",
    "LSC-L2-P8LTD": "warranty / support contract, not a product",
}

# Manufacturers that are placeholders, bespoke fabricators or 'assumed'
# suppliers - nothing to look up until the supplier is actually confirmed.
UNRESEARCHABLE_MFR = {
    "": "no manufacturer recorded",
    "-": "no manufacturer recorded",
    "—": "no manufacturer recorded",
    "N/A": "no manufacturer recorded",
    "CUSTOM": "bespoke / custom fabrication",
    "CBM Millwork": "bespoke joinery by CBM Millwork",
    "CBMmart": "bespoke fabrication",
    "Assumed ES Windows": "supplier not yet confirmed ('assumed')",
    "MCE": "supplier not yet confirmed",
    "Square D / Siemens or eq": "'or equal' - product not yet selected",
}


def main(argv):
    for s in (sys.stdout, sys.stderr):
        try:
            s.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass

    dry = "--dry-run" in argv

    data = json.loads(SEED.read_text(encoding="utf-8"))
    by_model = json.loads(FINDINGS.read_text(encoding="utf-8"))["by_model"]

    filled, already, missing = [], [], []

    for it in data["items"]:
        if it["spec_url"]:
            already.append(it)
            continue
        url = by_model.get(it["model"])
        if url:
            if not dry:
                it["spec_url"] = url
            filled.append(it)
        else:
            missing.append(it)

    if not dry:
        data["meta"]["research_pass"] = {
            "date": "2026-09-07",
            "filled": len(filled),
            "from_source": len(already),
            "still_missing": len(missing),
            "rule": ("official manufacturer domains only; where a datasheet "
                     "could not be confirmed the field is left blank rather "
                     "than guessed"),
        }
        SEED.write_text(json.dumps(data, ensure_ascii=False, indent=2),
                        encoding="utf-8")
        write_log(data["items"], filled, already, missing)

    total = len(data["items"])
    print("from source workbook : %d" % len(already))
    print("filled by research   : %d" % len(filled))
    print("still blank          : %d" % len(missing))
    print("documented           : %d / %d  (%.0f%%)"
          % (len(already) + len(filled), total,
             100.0 * (len(already) + len(filled)) / total))
    if dry:
        print("\n(dry run - nothing written)")


def reason_for(it):
    if it["model"] in NOT_A_PRODUCT:
        return NOT_A_PRODUCT[it["model"]]
    if it["manufacturer"] in UNRESEARCHABLE_MFR:
        return UNRESEARCHABLE_MFR[it["manufacturer"]]
    if not it["model"]:
        return "no model / SKU recorded"
    return "no official datasheet confirmed - needs manual lookup"


def write_log(items, filled, already, missing):
    total = len(items)
    done = len(already) + len(filled)

    out = []
    out.append("# Datasheet research log")
    out.append("")
    out.append("GP1-MUR Material & Hardware Register. Generated by "
               "`merge_research.py`; do not edit by hand.")
    out.append("")
    out.append("**Rule applied:** official manufacturer domains only - no "
               "reseller PDFs, no aggregators. Where a datasheet could not be "
               "confirmed as the right product, `spec_url` is left **blank** "
               "rather than guessed, for manual lookup.")
    out.append("")
    out.append("| | Items |")
    out.append("|---|---|")
    out.append("| Already linked in the source workbook | %d |" % len(already))
    out.append("| Filled by this research pass | %d |" % len(filled))
    out.append("| Still blank | %d |" % len(missing))
    out.append("| **Documented** | **%d / %d (%.0f%%)** |"
               % (done, total, 100.0 * done / total))
    out.append("")

    out.append("## Filled by research")
    out.append("")
    out.append("| # | Discipline | Item | Manufacturer | Model | Datasheet |")
    out.append("|---|---|---|---|---|---|")
    for it in sorted(filled, key=lambda x: x["seq"]):
        out.append("| %d | %s | %s | %s | %s | [link](%s) |" % (
            it["seq"], it["discipline"], md(it["item"]),
            md(it["manufacturer"]), md(it["model"]), it["spec_url"]))
    out.append("")

    out.append("## Already linked in the source workbook")
    out.append("")
    out.append("| # | Discipline | Item | Datasheet |")
    out.append("|---|---|---|---|")
    for it in sorted(already, key=lambda x: x["seq"]):
        out.append("| %d | %s | %s | [link](%s) |" % (
            it["seq"], it["discipline"], md(it["item"]), it["spec_url"]))
    out.append("")

    out.append("## Still blank - to fill in manually")
    out.append("")
    grouped = defaultdict(list)
    for it in missing:
        grouped[reason_for(it)].append(it)
    for reason in sorted(grouped, key=lambda r: -len(grouped[r])):
        group = sorted(grouped[reason], key=lambda x: x["seq"])
        out.append("### %s (%d)" % (reason, len(group)))
        out.append("")
        out.append("| # | Discipline | Item | Manufacturer | Model |")
        out.append("|---|---|---|---|---|")
        for it in group:
            out.append("| %d | %s | %s | %s | %s |" % (
                it["seq"], it["discipline"], md(it["item"]),
                md(it["manufacturer"]) or "-", md(it["model"]) or "-"))
        out.append("")

    LOG.write_text("\n".join(out), encoding="utf-8")


def md(s):
    """Escape the pipe so a value never breaks the markdown table."""
    return (s or "").replace("|", "\\|")


if __name__ == "__main__":
    main(sys.argv)
